### ISSUE TITLE
how to use with conjuctino with home-manager

### ISSUE THREAD

**Issue by adrian-gierakowski** [lf-/flakey-profile#2]
Thanks for this great project!

I love it's simplicity and easy of use. But I'd also like to be able to re-use various home-manager modules to declarative manage my home dir without re-inventing the wheel. Any idea how the two could be combined?

**Comment by lf-** [comment]
This is outside the goals of the project (since its main goal is being trivially simple) and I am somewhat confused by the feature request, as home-manager already provides declarative package management that is nicer in a couple ways though has much more complexity.

However you could add a flakey profile to environment.homePackages i guess, I'm not sure what it would gain you though. Alternatively add another PATH entry that points to a profile path, then pass --profile like `nix run .#profile.switch -- --profile /nix/var/nix/profiles/per-user/$USER/another-profile` (and make a wrapper script to do so).
